### Question 2

In [1]:
import torch
import numpy as np

In [2]:
x = torch.rand(7,7)
x

tensor([[4.8826e-01, 8.3791e-01, 6.2990e-01, 9.0450e-01, 3.0457e-01, 6.3186e-01,
         6.1316e-01],
        [6.1330e-02, 5.4964e-02, 9.0304e-01, 5.9114e-02, 3.7869e-01, 5.7951e-02,
         3.7143e-01],
        [1.3692e-01, 4.3116e-01, 3.0910e-01, 4.8433e-01, 1.9789e-02, 5.3037e-01,
         6.1699e-01],
        [3.2607e-01, 8.6667e-01, 5.0229e-01, 3.2403e-01, 9.9055e-01, 2.4681e-01,
         7.7350e-01],
        [7.6183e-01, 5.5816e-01, 3.0179e-01, 4.7811e-01, 3.6570e-01, 4.8194e-01,
         5.8772e-01],
        [9.1477e-02, 5.5172e-01, 1.8388e-01, 8.8845e-01, 7.8117e-01, 6.7144e-02,
         5.5066e-01],
        [7.4860e-01, 4.9485e-01, 4.4775e-04, 2.3845e-01, 8.1013e-01, 4.4980e-01,
         5.3100e-02]])

## Question 3

In [3]:
y = torch.rand(1,7)

z = torch.matmul(x, y.T)
z

tensor([[2.1092],
        [1.3267],
        [1.2092],
        [2.1224],
        [1.6220],
        [1.6473],
        [1.2712]])

## Question 4

In [4]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
x = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
y = torch.rand(1,7)

print(x)
print(y)

z = torch.matmul(x, y.T)
print(z)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


## Question 5

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"


RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
torch.cuda.manual_seed(RANDOM_SEED)
x = torch.rand(2,3).to(device)

torch.manual_seed(RANDOM_SEED)
torch.cuda.manual_seed(RANDOM_SEED)
y = torch.rand(2,3).to(device)

print(x)
print(y)

z = torch.matmul(x, y.T)
print(z)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')


## Question 6

In [6]:
z.max().item(), z.min().item()

(0.628727912902832, 0.21611443161964417)

## Question 7

In [7]:
z.argmax().item(), z.argmin().item()

(3, 1)

## Combined 5,6,7

In [8]:
import torch

# Set random seeds for reproducibility
torch.manual_seed(1234)          # CPU random seed
torch.cuda.manual_seed(1234)      # GPU random seed

# Create two random tensors of shape (2, 3)
tensor_a = torch.rand(2, 3).cuda()  # Send to GPU

torch.manual_seed(1234)          # CPU random seed
torch.cuda.manual_seed(1234)      # GPU random seed
tensor_b = torch.rand(2, 3).cuda()  # Adjust shape for matrix multiplication

# Perform matrix multiplication
result = torch.matmul(tensor_a, tensor_b.T)

# Find the maximum and minimum values
max_value = result.max().item()
min_value = result.min().item()

# Find the indices of the maximum and minimum values
max_index = result.argmax().item()
min_index = result.argmin().item()

# Display the results
print("Result of matrix multiplication:\n", result)
print("Maximum value:", max_value)
print("Minimum value:", min_value)
print("Index of maximum value:", max_index)
print("Index of minimum value:", min_index)

Result of matrix multiplication:
 tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')
Maximum value: 0.628727912902832
Minimum value: 0.21611443161964417
Index of maximum value: 3
Index of minimum value: 1
