In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
print(torch.version.cuda)

if (torch.cuda.is_available()):
    device = torch.device("cuda")
    print("Using GPU")

2.4.1
12.4
Using GPU


### Creating Tensors

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

#### Working with Tensors

In [4]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [5]:
TENSOR.ndim

3

In [6]:
TENSOR.shape

torch.Size([1, 3, 3])

In [7]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
TENSOR[0][1]

tensor([4, 5, 6])

#### Random Tensors

In [9]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9410, 0.1535, 0.3085, 0.6455],
        [0.3204, 0.6260, 0.8675, 0.1181],
        [0.6973, 0.6167, 0.7560, 0.0340]])

##### Zeros

In [10]:
zeroes = torch.zeros(size = (3,4))
print(zeroes* random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


##### Ones

In [11]:
ones = torch.ones(size = (3,4))
print(ones* random_tensor)

tensor([[0.9410, 0.1535, 0.3085, 0.6455],
        [0.3204, 0.6260, 0.8675, 0.1181],
        [0.6973, 0.6167, 0.7560, 0.0340]])


### Tensors and Tensors-like

In [12]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
one_to_ten_with_step = torch.arange(0,10,3)
one_to_ten_with_step

tensor([0, 3, 6, 9])

In [14]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
ten_rand = torch.rand_like(one_to_ten, dtype = torch.float)
ten_rand

tensor([0.4171, 0.2431, 0.4787, 0.9909, 0.1404, 0.8651, 0.4460, 0.3437, 0.1603,
        0.4281])

### Tensor Datatypes

In [16]:
tensor_float32 = torch.tensor([1,2,3], 
                            dtype = torch.float32, # or torch.float
                            device = device, # signifies the device to be used
                            requires_grad = False) # whether to track the gradients

#### Three big problems one runs into:
1. Tensors not of right datatype
2. Tensors not of right shape
3. Tensors not on the correct device

In [17]:
tensor_float32.dtype
tensor_float32.device

device(type='cuda', index=0)

In [18]:
convert_tensor_to_float16 = tensor_float32.type(torch.float16)
convert_tensor_to_float16

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

### Tensor Operation

Tensor operation inclued:
* Addition
* Subtraction
* Multiplication
* Division
* `Matrix Multiplication`

In [19]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [20]:
tensor+10

tensor([11, 12, 13])

In [21]:
tensor

tensor([1, 2, 3])

In [22]:
tensor = tensor*10
tensor

tensor([10, 20, 30])

In [23]:
tensor = tensor/10
tensor

tensor([1., 2., 3.])

In [24]:
tensor = tensor ** 2
tensor

tensor([1., 4., 9.])

#### Matrix Multiplication

In [25]:
tensor1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor2 = torch.tensor([[9,8,7],[6,5,4],[3,2,1],[6,7,8]])

print(tensor1)
print(tensor2)

print("since shape is not correct we will transpore tensor2")

tensor2 = tensor2.T

print(tensor2)

torch.matmul(tensor1, tensor2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1],
        [6, 7, 8]])
since shape is not correct we will transpore tensor2
tensor([[9, 6, 3, 6],
        [8, 5, 2, 7],
        [7, 4, 1, 8]])


tensor([[ 46,  28,  10,  44],
        [118,  73,  28, 107],
        [190, 118,  46, 170]])

In [26]:
tensor1 * tensor1 # element wise multiplication

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

### Tensor Aggregation

* min
* max
* sum
* mean

In [27]:
x = torch.arange(0,11)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
x.max(), torch.max(x)

(tensor(10), tensor(10))

In [29]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [30]:
# x.mean() results in an error of datatype therefore we will convert it to float

torch.mean(x.type(torch.float32))

tensor(5.)

In [31]:
x.argmin() # this returns the index of the minimum value

tensor(0)

In [32]:
x.argmax() # this returns the index of the maximum value

tensor(10)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshape - Reshapes a tensor to a given shape
* View - Shares a memory with the original tensor as well
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from the tensors
* Unsqueeze - Adds a `1` dimensions to a target tensor
* Permute - Return a view of the tensor with dimensions permuted in a certain way 

### Reshape and View

In [33]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
x_reshaped = x.reshape(9,1)
x_reshaped, x.shape, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9]),
 torch.Size([9, 1]))

In [35]:
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [36]:
z[1][2] = 8.
x # we can see that x is also changed upon changing z

tensor([1., 2., 3., 4., 5., 8., 7., 8., 9.])

In [37]:
x.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 8., 7., 8., 9.]])

### Stacking

In [38]:
x_stacked = torch.stack([x, x, x, x], dim=0) # stack along the first dimension
# what stacking along the first dimension means is that the shape of the resulting tensor will be (4, 9) as the earlier shape was 1,9
# therefore the first dimension is 4 and the second dimension is 9

x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 8., 7., 8., 9.],
         [1., 2., 3., 4., 5., 8., 7., 8., 9.],
         [1., 2., 3., 4., 5., 8., 7., 8., 9.],
         [1., 2., 3., 4., 5., 8., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [39]:
x_stacked = torch.stack([x, x, x, x], dim=1) # stack along the second dimension
# what stacking along the second dimension means is that the shape of the resulting tensor will be (9, 4) as the earlier shape was 1,9
# therefore the first dimension is 9 and the second dimension is 4

x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [8., 8., 8., 8.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

### Squeeze and unsqueeze

In [40]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [41]:
x.squeeze().size() # removes all the dimensions of size 1

torch.Size([2, 2, 2])

In [42]:
x.squeeze(dim = 1).size() # only the 1 dimension will be squeezed

torch.Size([2, 2, 1, 2])

In [43]:
x.squeeze(dim = 2).size() # since the dimension is not 1, it will not be squeezed

torch.Size([2, 1, 2, 1, 2])

In [44]:
x = torch.arange(0,9)
x
x.reshape(9,1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [45]:
x = x.squeeze()
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
x.unsqueeze(dim = 0), x.unsqueeze(dim = 0).shape # adds a dimension of size 1 at the 0th index

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 9]))

In [47]:
x = x.unsqueeze(dim = 1)
x, x.shape # adds a dimension of size 1 at the 1st index 

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]]),
 torch.Size([9, 1]))

### Permute

In [48]:
# this shares the memory with the original tensor. A way to remember it is that it switches the dimensions of a tensor

x = torch.randn(2,3,5)
print(x.shape)
x = x.permute([2,0,1]) # places the 2nd dimension (5) at the 0th index, the 0th dimension (2) at the 1st index and the 1st (3) dimension at the 2nd index
print(x.shape)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [49]:
# in the context of images

x = torch.rand(224, 224, 3)
print(x.shape)
x = x.permute([2,0,1]) # now the color channel is at the 0th index, the height is at the 1st index and the width is at the 2nd index
print(x.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## Indexing tensors

In [50]:
x = torch.arange(1,10).reshape(1,3,3)
y = torch.arange(10,19).reshape(1,3,3)
x = torch.stack([x,y])
x = x.squeeze()
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [51]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
x[0][0]

tensor([1, 2, 3])

In [53]:
x[0][0][0]

tensor(1)

In [54]:
x[:, 0] # all the elements of the first dimension and the first element of the second dimension

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [55]:
x[:, :, 1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

In [56]:
x[:,:,2]

tensor([[ 3,  6,  9],
        [12, 15, 18]])

## Pytorch and Numpy

* Numpy to tensor -> `torch.from_numpy(ndarray)`
* Tensor to Numpy -> `torch.Tensor.numpy()`

In [57]:
array = np.array([1,2,3])

# the default dtype is float64 for numpy so we need to convert it to float32 to match the default dtype of torch
tensor = torch.from_numpy(array).type(torch.float32) 

tensor, tensor.dtype, array.dtype

(tensor([1., 2., 3.]), torch.float32, dtype('int64'))

In [58]:
tensor = torch.rand(2,3)
array = tensor.numpy()
array

array([[0.8659072 , 0.3694986 , 0.21010506],
       [0.09349579, 0.8324162 , 0.33024842]], dtype=float32)

In [59]:
array.dtype, tensor.dtype

(dtype('float32'), torch.float32)

## Reproducibility

In [60]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_a = torch.tensor([1,2,3])

torch.manual_seed(RANDOM_SEED)
tensor_b = torch.tensor([1,2,3])

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([True, True, True])


## GPU use

In [61]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [62]:
tensor = torch.rand(3,4)
tensor, tensor.device

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 device(type='cpu'))

In [63]:
tensor_to_gpu = tensor.to(device)
tensor_to_gpu, tensor_to_gpu.device

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]], device='cuda:0'),
 device(type='cuda', index=0))

In [64]:
tensor_to_numpy = tensor_to_gpu.cpu().numpy()
tensor_to_numpy

array([[0.88226926, 0.91500396, 0.38286376, 0.95930564],
       [0.3904482 , 0.60089535, 0.25657248, 0.7936413 ],
       [0.94077146, 0.13318592, 0.9345981 , 0.59357965]], dtype=float32)